[build]
  command = "npm run db:generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "10.2.3"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"