
// src/app/api/admin/tickets/[id]/route.ts - Individual ticket management
// src/app/api/admin/tickets/route.ts - Tickets management API
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { TicketService } from '@/lib/ticketService'

export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const ticketId = params.id
    const body = await request.json()
    const { action, notes, adminUser } = body
    
    const ticket = await prisma.ticket.findUnique({
      where: { id: ticketId },
      include: { registration: true }
    })
    
    if (!ticket) {
      return NextResponse.json(
        { success: false, message: 'Ticket not found' },
        { status: 404 }
      )
    }
    
    let updateData: any = {}
    let result: any = {}
    
    switch (action) {
      case 'SEND':
        updateData = {
          status: 'SENT',
          sentAt: new Date()
        }
        result.message = 'Ticket marked as sent'
        break
        
      case 'COLLECT':
        updateData = {
          status: 'COLLECTED',
          collectedAt: new Date(),
          collectedBy: adminUser || 'Admin'
        }
        result.message = 'Ticket marked as collected'
        break
        
      case 'USE':
        updateData = {
          status: 'USED'
        }
        // Create check-in record
        await prisma.ticketCheckIn.create({
          data: {
            ticketId: ticket.id,
            checkedInBy: adminUser || 'Admin',
            notes: notes || 'Checked in by admin'
          }
        })
        result.message = 'Ticket checked in successfully'
        break
        
      case 'CANCEL':
        updateData = {
          status: 'CANCELLED'
        }
        result.message = 'Ticket cancelled'
        break
        
      case 'REGENERATE':
        // Generate new QR code and ticket number
        const newTicketData = await TicketService.createTicket(ticket.registrationId, ticket.ticketSequence || 1)
        updateData = {
          ticketNumber: newTicketData.ticketNumber,
          qrCode: newTicketData.qrCode,
          status: 'GENERATED',
          issuedAt: new Date(),
          sentAt: null,
          collectedAt: null
        }
        result.message = 'Ticket regenerated with new number'
        result.newTicketNumber = newTicketData.ticketNumber
        break
        
      default:
        return NextResponse.json(
          { success: false, message: 'Invalid action' },
          { status: 400 }
        )
    }
    
    // Update ticket
    const updatedTicket = await prisma.ticket.update({
      where: { id: ticketId },
      data: updateData
    })
    
    // Log the action
    await prisma.emailLog.create({
      data: {
        registrationId: ticket.registrationId,
        emailType: 'TICKET_DELIVERY',
        subject: `Ticket ${action} - ${ticket.ticketNumber}`,
        recipient: ticket.registration.email,
        status: 'SENT'
      }
    })
    
    return NextResponse.json({
      success: true,
      ...result,
      data: {
        ticket: updatedTicket
      }
    })
    
  } catch (error: any) {
    console.error('Error updating ticket:', error)
    return NextResponse.json(
      { success: false, message: 'Failed to update ticket', error: error.message },
      { status: 500 }
    )
  }
}

// src/app/api/admin/tickets/generate/route.ts - Generate new tickets
export async function POST(request: NextRequest) {
  try {
    const { registrationId, quantity = 1, adminUser } = await request.json()
    
    if (!registrationId) {
      return NextResponse.json(
        { success: false, message: 'Registration ID is required' },
        { status: 400 }
      )
    }
    
    const registration = await prisma.registration.findUnique({
      where: { id: registrationId }
    })
    
    if (!registration) {
      return NextResponse.json(
        { success: false, message: 'Registration not found' },
        { status: 404 }
      )
    }
    
    // Generate multiple tickets
    const generatedTickets = await TicketService.createMultipleTickets(registrationId, quantity)
    
    // Log ticket generation
    await prisma.emailLog.create({
      data: {
        registrationId,
        emailType: 'TICKET_DELIVERY',
        subject: `${quantity} Ticket(s) Generated by Admin`,
        recipient: registration.email,
        status: 'SENT'
      }
    })
    
    return NextResponse.json({
      success: true,
      message: `Successfully generated ${quantity} ticket(s)`,
      data: {
        tickets: generatedTickets,
        registration: {
          id: registration.id,
          name: `${registration.firstName} ${registration.lastName}`,
          email: registration.email
        }
      }
    })
    
  } catch (error: any) {
    console.error('Error generating tickets:', error)
    return NextResponse.json(
      { success: false, message: 'Failed to generate tickets', error: error.message },
      { status: 500 }
    )
  }
}

// src/app/api/admin/tickets/download/[id]/route.ts - Admin ticket download
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const ticketId = params.id
    
    const ticket = await prisma.ticket.findUnique({
      where: { id: ticketId },
      include: {
        registration: true
      }
    })
    
    if (!ticket) {
      return NextResponse.json(
        { success: false, message: 'Ticket not found' },
        { status: 404 }
      )
    }
    
    // Redirect to the download API with registration ID
    const downloadUrl = `/api/tickets/download?registrationId=${ticket.registrationId}`
    return NextResponse.redirect(new URL(downloadUrl, request.url))
    
  } catch (error: any) {
    console.error('Error downloading ticket:', error)
    return NextResponse.json(
      { success: false, message: 'Failed to download ticket', error: error.message },
      { status: 500 }
    )
  }
}